// View models for all entities
// Generated by http://json2ts.com/
// after pasting results from my Teams API

export class Employee {
  _id: string;
  FirstName: string;
  LastName: string;
  AddressStreet: string;
  AddressState: string;
  AddressCity: string;
  AddressZip: string;
  PhoneNum: string;
  Extension: number;
  Position: Position;
  HireDate: string;
  SalaryBonus: number;
  __v: number;
}

export class Project {
  _id: string;
  ProjectName: string;
  ProjectDescription: string;
  ProjectStartDate: string;
  ProjectEndDate?: any;
  __v: number;
}

export class Position {
  _id: string;
  PositionName: string;
  PositionDescription: string;
  PositionBaseSalary: number;
  __v: number;
}

export class Team {
  _id: string;
  TeamName: string;
  // TeamLead: Employee = new Employee();
  TeamLead: Employee;
  __v: number;
  // Employees: Employee[] = [];
  // Projects: Project[] = [];
  Employees: Employee[];
  Projects: Project[];
}

// User account

export class UserAccount {
  userName: string;
  fullName: string;
  dateOfBirth: string;
  dateCreated: string;
  userKind: string;
  pin: number;
  activeUser: boolean;
}




